import { mkdir, writeFile, readFile } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

const CIRCLECI_CONFIG = `# Auto-generated by lemonx — AI-powered test generation, execution, and self-healing fixes
# Environment variables required in CircleCI project settings:
#   LEMON_WEBHOOK_URL    — your tunnel URL (e.g. https://abc123.ngrok-free.app)
#   LEMON_WEBHOOK_SECRET — must match the secret from \`npx lemonx init\`

version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.0
    working_directory: ~/project

jobs:
  ai-test-loop:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Trigger AI test-fix loop
          command: |
            echo "🍋 Sending webhook to lemonx agent server..."

            PAYLOAD=$(jq -n \\
              --arg repo "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" \\
              --arg branch "$CIRCLE_BRANCH" \\
              --arg commit "$CIRCLE_SHA1" \\
              --arg targetDir "$(pwd)" \\
              '{repoUrl: $repo, branch: $branch, commitSha: $commit, targetDir: $targetDir}')

            echo "Payload: $PAYLOAD"

            STATUS_CODE=$(curl -s -w "%{http_code}" -o /tmp/webhook_response.txt \\
              -X POST "$LEMON_WEBHOOK_URL/webhook/test-and-fix" \\
              -H "Content-Type: application/json" \\
              -H "X-Webhook-Signature: $LEMON_WEBHOOK_SECRET" \\
              -d "$PAYLOAD")

            echo "Status Code: $STATUS_CODE"
            echo "-------- Response --------"
            cat /tmp/webhook_response.txt || true
            echo "--------------------------"

            if [ "$STATUS_CODE" -ne 200 ]; then
              echo "❌ Webhook failed with status $STATUS_CODE"
              exit 1
            fi

            echo "✅ Webhook accepted. AI agents are working..."

  ai-generate-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Trigger AI test generation
          command: |
            PAYLOAD=$(jq -n \\
              --arg repo "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" \\
              --arg branch "$CIRCLE_BRANCH" \\
              --arg commit "$CIRCLE_SHA1" \\
              --arg targetDir "$(pwd)" \\
              '{repoUrl: $repo, branch: $branch, commitSha: $commit, targetDir: $targetDir}')

            STATUS_CODE=$(curl -s -w "%{http_code}" -o /tmp/webhook_response.txt \\
              -X POST "$LEMON_WEBHOOK_URL/webhook/generate-tests" \\
              -H "Content-Type: application/json" \\
              -H "X-Webhook-Signature: $LEMON_WEBHOOK_SECRET" \\
              -d "$PAYLOAD")

            echo "Status Code: $STATUS_CODE"
            cat /tmp/webhook_response.txt || true

            if [ "$STATUS_CODE" -ne 200 ]; then
              echo "❌ Test generation failed"
              exit 1
            fi

  ai-run-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Trigger AI test execution
          command: |
            PAYLOAD=$(jq -n \\
              --arg repo "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" \\
              --arg branch "$CIRCLE_BRANCH" \\
              --arg commit "$CIRCLE_SHA1" \\
              --arg targetDir "$(pwd)" \\
              '{repoUrl: $repo, branch: $branch, commitSha: $commit, targetDir: $targetDir}')

            STATUS_CODE=$(curl -s -w "%{http_code}" -o /tmp/webhook_response.txt \\
              -X POST "$LEMON_WEBHOOK_URL/webhook/run-tests" \\
              -H "Content-Type: application/json" \\
              -H "X-Webhook-Signature: $LEMON_WEBHOOK_SECRET" \\
              -d "$PAYLOAD")

            echo "Status Code: $STATUS_CODE"
            cat /tmp/webhook_response.txt || true

            if [ "$STATUS_CODE" -ne 200 ]; then
              echo "❌ Test execution failed"
              exit 1
            fi

workflows:
  ai-test-and-fix:
    jobs:
      - ai-test-loop:
          filters:
            branches:
              ignore: main
`;

async function init() {
  const targetDir = process.argv[3] || process.cwd();
  const circleciDir = join(targetDir, ".circleci");

  console.log("🍋 lemonx init — setting up CircleCI AI test integration\n");

  if (!existsSync(targetDir)) {
    console.error(`❌ Directory not found: ${targetDir}`);
    process.exit(1);
  }

  await mkdir(circleciDir, { recursive: true });

  const configPath = join(circleciDir, "config.yml");
  const exists = existsSync(configPath);

  if (exists) {
    const existing = await readFile(configPath, "utf-8");
    if (existing.includes("lemonx") || existing.includes("LEMON_WEBHOOK_URL")) {
      console.log("⚠️  CircleCI config already contains lemonx integration. Skipping.");
      console.log(`   Config: ${configPath}`);
      return;
    }
    console.log(`⚠️  Existing CircleCI config found at: ${configPath}`);
    console.log("   Back it up before overwriting.\n");
  }

  await writeFile(configPath, CIRCLECI_CONFIG, "utf-8");
  console.log(`✅ CircleCI config written to: ${configPath}`);

  const secret = crypto.randomUUID().replace(/-/g, "").slice(0, 32);
  console.log(`\n🔐 Your webhook secret: ${secret}`);
  console.log("\nNext steps:");
  console.log("1. In CircleCI project settings, add these environment variables:");
  console.log("   LEMON_WEBHOOK_URL    — your tunnel URL (get it from \`npx lemonx tunnel\`)");
  console.log("   LEMON_WEBHOOK_SECRET — the secret above");
  console.log("\n2. Start the webhook server on your machine:");
  console.log("   npx lemonx start");
  console.log("\n3. Start a tunnel to expose your server:");
  console.log("   npx lemonx tunnel");
  console.log("\n4. Push to any branch (not main) and CircleCI will trigger the AI test loop!");
}

import crypto from "crypto";

await init();
